### ISSUE TITLE
[BUG] 游戏无法启动

### ISSUE THREAD

**Issue by LCEN1361** [HopiHopy/PojavZenithHorizon#48]
### 问题描述

 选择指定的本地整合包，启动游戏后弹出错误，点确定后什么都没有发生（游戏不启动）
 我因为fcl糟糕的优化尝试pojav，整合包是我自己组的，在fcl上正常运行。pojav也正确认出了我的整合包。切换渲染器/java版本微软/离线登录错误仍旧。
我注意到游戏每次点击启动都会下载游戏文件，但我使用魔法后还是不行。
我该怎么做？

### 日志/截图或视频

![Uploading Screenshot_2024-06-11-16-56-12-861_net.kdt.pojavlaunch.zh.jpg…]()

java.lang.NullPointerException: Attempt to read from field 'net.kdt.pojavlaunch.JMinecraftVersionList$FileProperties net.kdt.pojavlaunch.JMinecraftVersionList$LoggingConfig$LoggingClientConfig.file' on a null object reference in method 'void net.kdt.pojavlaunch.Tools.launchMinecraft(androidx.appcompat.app.AppCompatActivity, net.kdt.pojavlaunch.value.MinecraftAccount, net.kdt.pojavlaunch.value.launcherprofiles.MinecraftProfile, java.lang.String, int)'
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:205)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:385)
	at net.kdt.pojavlaunch.MainActivity.lambda$initLayout$7$net-kdt-pojavlaunch-MainActivity(MainActivity.java:237)
	at net.kdt.pojavlaunch.MainActivity$$ExternalSyntheticLambda13.isReady(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.MinecraftGLSurface.lambda$realStart$0$net-kdt-pojavlaunch-MinecraftGLSurface(MinecraftGLSurface.java:371)
	at net.kdt.pojavlaunch.MinecraftGLSurface$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

### 复现步骤

```markdown
在上面
```

### 预期行为

游戏正常启动

### 其他信息

```markdown
- 设备型号：小米14
- CPU 架构：arm64
- Android 版本：14
- PojavZH 版本：1211
```

**Comment by HopiHopy** [comment]
缺少整合包详细信息，无法复现，暂关闭此议题
