### ISSUE TITLE
1.7.10无法加入拔刀剑

### ISSUE THREAD

**Issue by lyanye33** [HopiHopy/PojavZenithHorizon#63]
### 问题描述

1.7.10版本加入拔刀剑会错误代码退出
这个情况从pojav原版就有 在fcl和hmclpe均没有这种情况

### 日志/截图或视频

![S40702-15385199_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZenithHorizon/assets/174421274/84946257-c54c-4afe-963a-105275b7f260)

错误信息
java.io.IOException: close failed: EIO (I/O error)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.FileInputStream.close(FileInputStream.java:439)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:476)
	at l.ۘۨۜ.ۡ(KB3F:299)
	at l.ۘۨۜ.ۡ(Native Method)
	at l.ۜۗۜ.call(WB2Q:396)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: close failed: EIO (I/O error)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 9 more

### 复现步骤

```markdown
打开启动器
加入拔刀剑
启动1.7.10
错误代码退出
```

### 预期行为

。

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.4

### 其他信息

```markdown
- 设备型号：魅族20
- CPU 架构：1xQualcomm@ Cortex-X32xQualcomm® Cortex-A7102xQualcomm® Cortex-A7153x Qualcomm@ Cortex-A510
- GPU 信息：骁龙8gen2
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by HopiHopy** [comment]
@lyanye33 你所分享的“错误信息”为MT管理器报错，并非实际错误报告或日志，请发布准确的日志报告
